### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jasonkarns** [mhagger/git-imerge#103]
I love using git-imerge but the homebrew formula is missing bash completion because there hasn't been a stable/tagged release that includes completion.

**Comment by mhagger** [comment]
Yeah, a release is long overdue. Let me try to get #104 merged and then I'll add a tag. (If you have an idea of how bash completion works internally or even if you don't mind doing some testing, your help reviewing that PR would be welcome since I have no *idea* what I'm doing in that department :wink:.)

**Comment by mhagger** [comment]
I just created a release `v1.0.0` (note that the tag has a leading `v`, unlike the tag for release `0.7.0`).
