### ISSUE TITLE
Gracefully continue after an aborted merge

### ISSUE THREAD

**Issue by mulle-nat** [mhagger/git-imerge#106]
So predictably I got confused by a merge, about 5 hours into git imerging. I figured before I commit something very wrong, I abort the merge and let git imerge reprompt me.

This does not happen, instead it says

```
$ git merge --abort
$ git-imerge continue
Commit 31c2ace01cd59c50a9a41ab85b69b4f1a92c089e is not usable; it is not a pairwise merge of adjacent parents
$ git log
commit 31c2ace01cd59c50a9a41ab85b69b4f1a92c089e
Merge: 4b4684f 0e02965
Author: Nat! 
Date:   Mon Sep 12 13:27:44 2016 +0200

    imerge 'mulle_objclang_39': automatic merge 11-22
```

I suspect I could restart it manually somehow. Ideally `imerge continue` should just try to merge again IMO.

**Comment by mhagger** [comment]
If you check out some other branch, delete imerge's temporary branch (the name looks something like `refs/heads/imerge/$NAME`), and type `git-imerge continue`, you should be able to continue where you left off. Be sure to delete the reference under `refs/heads/`, *not* any references under `refs/imerge/`!

It would obviously be nice if this were easier.

**Comment by waldyrious** [comment]
This is related to #101 -- I believe that functionality would work perfectly for this use case. Can you confirm, @mulle-nat?

**Comment by mulle-nat** [comment]
Looks related, that's as much as I can say. :)

**Comment by mhagger** [comment]
The way I read this issue is that @mulle-nat had a problem with a single micromerge and wanted to start the micromerge over without aborting the overall imerge. Whereas #101 is about aborting the whole imerge while preserving progress that has been made so far in the form of, for example, a rebase of the branch to some commit that is nearer, but not all of the way to, the other branch tip.

**Comment by waldyrious** [comment]
Oh, I see. Sorry for the noise, then.
