### ISSUE TITLE
Is it possible/desirable for imerge to ignore merge commits as potential "original commits" to a conflict?

### ISSUE THREAD

**Issue by benjaminpetrin** [mhagger/git-imerge#127]
I'm trying to understand if the following scenario is an artifiact of how my org works with git/github, or something that can be improved in imerge. For context, we have a master branch and a release branch representing the last release. The latest release gets continued support while master continues to evolve. The only way commits land on master or release branches is through a _merge_ PR, so that it can be reviewed. 

```
master:  0-1
release-1: \-a
```

Above, a release branch was cut from master and some commits, a, were added to it (for clarity i've omitted the branch being cut from release and merged in, but again since all merges go through a merge PR, that is the case). These commits are occasionally merged back into master and conflicts resolved. Since that too is done with a PR, it'll look like this:

```
            merge commit generated from merging the PR
                        v

master:  0-1-2-3-4-6-7--8
release-1: \-a-b-c   | /
merge-1           \--x/

                     ^
              merge commit on PR to bring release-1 changes into master
```

Above, a branch (merge-1) was cut, the conflicts with master were solved in x, and then this was brought back into master in a PR, resulting in merge commit 8. I think this is a standard way of working, but if not please let me know.

But that might not be the last time we merge release-1 into master. When we do it again, more commits will have been put onto the release branch (commit d) and more commits onto master (9 and 10)

```
master:  0-1-2-3-4-6-7--8-9-10-11
release-1: \-a-b-c   | /  -d   /
merge-1           \--x/     \-y
```

Now, when using imerge to solve the conflicts in y, it may identify the parents of a particular conflict as some commit 8 through 10 (totally understandable), but it will idenitfy commit x as the other parent. But commit X wasn't the commit that added the conflicting line, one of the commits a-c was.

The trouble is, I'm using imerge to try to identify the context for each of the original commits, and I would have expected to identify parents like 9 and b, but by identifying the merge commit I've lost the context (see note 2).

Is this an oversight of how imerge identifies the true parents of a conflict, or an artifact of how we are using github? If that later, I'd love to know how I should be doing this to avoid the problem.

Note: 
 1. if its important I'm using the latest version of imerge from this repo at the moment.
 1. Technically, 9 is a merge commit too, but its the merge commit from a PR for a single feature branch. Again, it _might_ make more sense to instead identify the actually commit that added the line, not the merge commit.

Can someone maybe explain what I'm doing wrong?

**Comment by mhagger** [comment]
I'm having trouble reading your diagram. Is this equivalent?

```
master:  0-1-2-3-4-6-7-- 8--9-10---11
          \           \ /       \ /
merge-1    \           x         y
            \         /         /
release-1:   a---b---c---------d
```

If I understand correctly, you want to use `imerge` to do the merge at `y`, right?

The merge base for this merge is `c`. (See `git-merge-base(1)` for the definition of the merge base.) All of the changes that were introduced by `a` and `b` are already in `8` via the merge of `x` into `master`. So at `y` there should be no merge conflicts that involve the changes that were made in `a` and `b`.

But all of the changes made in `0..7` appear to the merge as if they were made in commit `x`, because that is the first commit that is a descendant of `c` that includes those changes.

I think that if you had done a "merge with history" (i.e., retained the full incremental merge in your history), then you would have some additional context for the second imerge. Your history would look roughly like (I'm omitting some commits on master):

```
master:  0------1------2-------7---------------8--9-10---11
          \                     \             /       \ /
merge-1    \                     a'          /         y
            \                     \         /         /
             \                     b'      /         /
              \      other          \     /         /
               \                     c'  /         /
                \       stuff         \ /         /
		 \	               x         /
                  \        in         /         /
                   \                 7'        /
                    \        here   /         /
                     \             2'        /
                      \           /         /
                       \         1'        /
                        \       /         /
release-1:               a--b--c---------d
```

So you would have to merge the changes from `d` with the commits `1'`, `2'`, `7'`, `x`, `8`, `9`, and `10`, which is more or less the minimum that you could hope for. But retaining all that extra parentage information would be quite cumbersome given the current state of tooling.

I hope that helps!
