### ISSUE TITLE
port to Python 3

### ISSUE THREAD

**Issue by pabs3** [mhagger/git-imerge#148]
The Python 2 EOL is now passed and distros are starting to remove it. So it is going to become harder to run git-imerge. It would be great to see it ported to Python 3 soon.

https://pythonclock.org/
https://www.enricozini.org/blog/2020/python/python-2-is-dead/

**Comment by pabs3** [comment]
Hmm, the README says it already works with Python 3. So probably the script just needs to use `env python3` instead of `env python`.

**Comment by mhagger** [comment]
> So probably the script just needs to use `env python3` instead of `env python`.

I'm not sure what you mean, concretely. Honestly, I haven't kept up with Python evolution lately, and don't know much about the modern setup system. It used to be you could drop a file in your `$PATH` and be done with it :-) I'm guessing that somehow `setup.py` tells what Python version to use, but it seems to allow both Python2 and Python3 already.

If there is somebody who has the time and knowledge to be the "release manager", that would be great, because I don't have either one right now.

**Comment by pabs3** [comment]
I've submitted a pull request that shows the exact change needed.

https://github.com/mhagger/git-imerge/pull/154

I've tested this change locally and the script works fine with Python 3.

It is a totally awesome script btw, thanks so much for writing it.

The latest trend in Python packaging is pyproject.toml, I would suggest
dropping the setup.py from the setuptools branch and switching
to pyproject.toml. I'm not sure if setuptools or another Python
packaging tool should be used instead though.

https://snarky.ca/what-the-heck-is-pyproject-toml/
https://www.python.org/dev/peps/pep-0518/
https://www.python.org/dev/peps/pep-0517/

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by mhagger** [comment]
Fixed by `setuptools` changes.

**Comment by waldyrious** [comment]
> Fixed by `setuptools` changes.

Ref: #143
