### ISSUE TITLE
Exact equivalent of `git rebase --onto ancient origin/ancient modern` ?

### ISSUE THREAD

**Issue by rulatir** [mhagger/git-imerge#183]
I have several "rebase checkpoints" along a very long topic branch. When I rebase it on master, I rebase those checkpoints (represented as branches) in order. This helps me avoid aborting the whole rebase in the rare cases when I run into insurmountable difficulties near the end of the rebase.

After the rebase, I always push all the checkpoints to the repository so that I can have an `origin/` reference for each of them ready for the next rebase.

I rebase each checkpoint branch using the 3-argument `rebase --onto`. Assuming the previous successfully rebased checkpoint is named `ancient` and the one I want to rebase now is named `modern`, I use the following command:

```bash
git rebase --onto ancient origin/ancient modern
```

What is the exact git-imerge equivalent of this command?

**Comment by rulatir** [comment]
(Just realized I had already asked this exact question, sorry!)

**Comment by mhagger** [comment]
As you know, `git-imerge` doesn't have the equivalent of the `--onto` option.

If I understand your use case correctly, the _end effect_ of your multiple rebases would be the rebase of a full branch, which, if you did it directly, wouldn't need the `--onto` option. You only need the `--onto` option because you want to preserve some checkpoints. Is that correct?

If so, then IMO the correct solution to this problem would be for you to run a full `git imerge rebase`, but for `git-imerge` to make it possible to interrupt such a rebase while it is in progress even if it hasn't been completed. For example, see #101. That way you wouldn't need to do any additional manual bookkeeping but could still stop if you get stuck.

**Comment by rulatir** [comment]
The "correct solution" you propose sacrifices the **actual utility** of checkpoints, which is to make CERTAIN (as opposed to merely hoped for) that some ALREADY FIXED conflicts will NEVER have to be fixed again during subsequent attempts at completing the same rebase.
