### ISSUE TITLE
[Question] why is such a feature not integrated in git main?

### ISSUE THREAD

**Issue by LowLevelMahn** [mhagger/git-imerge#191]
the feature set is briliant - im currently upgrading 3 super old branches and it seems to work very good

im curious why there is no such feature directly in git availabe - man power/time thing, design weeknesses or just not much needed

what is the relation to the "git rerere" command here - less handwork?

**Comment by mhagger** [comment]
I'm glad that `git-imerge` is useful to you.

> im curious why there is no such feature directly in git availabe

Upstream Git didn't see a reason for `git-imerge` to be integrated into the main Git project, because it can survive as an independent project.

It would obviously get a lot more visibility upstream, and possibly more contributions (especially given that I haven't had much time to work on it in ages). On the other hand, if it were upstream that would imply some commitment from the Git project to maintain it, it's not always possible to find contributors for more niche projects like this, and it would force more work on the maintainer.

I also feel like `git-imerge` might have a limited target audience, consisting of people who are willing to learn how it works, which is conceptually more difficult than normal `git merge` / `git rebase`; and who maintain a relatively clean history, since `git-imerge` can currently only handle linear branches. So even if it were upstreamed, it might not become a standard tool.

If there were a clamour for this to become a standard part of Git and there were a bunch of people psyched about maintaining it, then there's nothing stopping them from trying to upstream it. I certainly wouldn't stand in the way and I intentionally chose a compatible license. But I personally can't commit to maintaining it; I have too little available time.

`git rerere` predates `git imerge` by a large margin, back in the days when independent Git-related projects had more trouble getting visibility. I don't think that the fact that `git rerere` is in upstream Git has much to say about whether `git-imerge` should be.
