### ISSUE TITLE
Commit X is not usable; its parents are not known merge commits

### ISSUE THREAD

**Issue by ggascoigne** [mhagger/git-imerge#72]
I'm dealing with a reasonably large merge and in several places files have been moved in conflicting ways on both sides of the merge.

If I was doing this by hand my usual approach is to do a test merge, see what the rename conflicts are.  Abort the merge, then manually move files around to make the move smoother.  Commit that changes then do the merge again.  If I get it right there are generally a pretty small number of conflicts at this point so fix them, and then before committing move the files on to where ever they really should have been on the target branch.

However, this now means that the merge is two commits and not one.

If I try and do this in the middle of an imerge I get the error:

Commit X is not usable; its parents are not known merge commits.

How would you recommend I get around this problem, is there some better way to do this?

**Comment by mhagger** [comment]
@ggascoigne: I'm sure this response is too late for you :disappointed:, but maybe it will be helpful for other people in the future.

When you run `git imerge continue`, it looks at the `HEAD` commit to see if it can be incorporated into the current imerge. It does this by looking at its two parents and checking whether they are two commits that currently need manual merging.

So, suppose imerge left the repo in the following state:

```
o---0---1---2---3
    |   |   |
    A---o---X
    |   |   |
    B---Y---?
    |
    C
```

It expected you to fill in the merge at `?` by merging `X` and `Y` directly, but instead (if I understand correctly) you did the merge via a helper commit `H`, maybe like:

```
o---0---1---2---3
    |   |   |
    A---o---X
    |   |   |
    B---Y-H-M
    |
    C
```

At this point `git imerge continue` fails for you, because one of the parents of your final merge `M` is the helper commit `H`, which is unknown to imerge. Therefore it doesn't recognize that `M` can be used as the merge between `X` and `Y`.

Fortunately, the solution isn't that difficult. You need to adjust the parents of `M` to be `X` and `Y` without changing its tree contents. You can do that using a handy-dandy command that I built into imerge even though it doesn't really fit there:

    git reset --hard $(git imerge reparent X Y)

This essentially squashes commit `H` into `M`, making the repo look like

```
o---0---1---2---3
    |   |   |
    A---o---X
    |   |   |
    B---Y---M'
    |
    C
```

Now `git imerge continue` should work.

It would be nice to make this easier. For example, we could check whether the `HEAD` commit has only two ancestors that are on the frontier of the merge and no ancestors that are not on the frontier. If so, we could check whether the merge of those two parents is needed, and if so, do essentially what I described above. But I would be a little bit worried that we were throwing away useful work done by the user. For example, what if you wrote a careful commit message for commit `H` explaining what you were changing and why it was necessary? You might be upset to have it discarded.

On an even deeper level, I wonder if your commit `H` would be useful for the continuation of the imerge? For example, when it comes time, in the next row, to fill in this `?`:

```
o---0---1---2---3
    |   |   |
    A---o---X
    |   |   |
    B---Y-H-M
    |   |   |
    C---T---?
```

it might actually be easier to first compute the merge of `H` and `T`, and then compute the merge of `M` and `U`:

```
o---0---1---2---3
    |   |   |
    A---o---X
    |   |   |
    B---Y-H-M
    |   | | |
    C---T-U-?
```

I think this is a promising idea, though I'm not sure if it generalizes. It would be quite a lot of work to build it into `git imerge`, because a lot of the code assumes a "rectangular grid" topology of commits and merges.

**Comment by mhagger** [comment]
I just added #79 to record the idea of supporting non-rectangular merge diagrams.

**Comment by leventelist** [comment]
Can you tell us how to determine the X and Y hashes in a generic way? Is that what the tool prints at the beginning like

Original first commit: xxxxxx

Original second commit: yyyyyyy
