### ISSUE TITLE
leaves empty [imerge] sections behind in .git/config

### ISSUE THREAD

**Issue by ghost** [mhagger/git-imerge#77]
I'm looking at my .git/config a few days after using git imerge serveral times and sometimes also resetting git-imerge runs. Now my .git/config contains several empty `[imerge]` sections.

It seems git imerge puts some state information there but doesn't always clean up properly? Is .git/config really the best place for state info?

**Comment by mhagger** [comment]
> I'm looking at my .git/config a few days after using git imerge serveral times and sometimes also resetting git-imerge runs. Now my .git/config contains several empty `[imerge]` sections.

This is a weakness of `git config` itself (which `git-imerge` uses to read/write configuration values). The extra empty sections don't actually do any harm, except to our sense of neatness.

> Is .git/config really the best place for state info?

I don't see why not. Most of the state info is stored as blob objects in the Git repository itself. The only state that is stored in config is the name of the imerge that is currently the one being worked on, which is needed to figure out the name of the reference that contains the rest of the information for that imerge.

If you have a concrete idea for improvement, please reopen this bug and let us know.

**Comment by thomas-koch-comsolit** [comment]
I can't reopen the bug, but I have an idea. Don't use a config file for state information. Configuration and state are two very different types of information. I hand edit config files and don't like tools to mess around with my handcrafted config file.

Please use a different file than .git/config or maybe a folder .git/imerge with one file per merge?

Please reopen this as nice-to-have. Would be an easy target for somebody starting to contribute to git-imerge. - Thank you!

**Comment by mhagger** [comment]
But the user's choice of which imerge to work on *is* a configuration setting--it's the user's choice of which imerge s/he wants to work on. The fact that this choice is made as a side effect of other commands doesn't change that fact.

I wouldn't want to invent an extra file just to hold that one little bit of information.

What I *can* imagine would be not to set `imerge.default` so eagerly. After all, if there is only a single imerge in progress (by far the most common case), it is not really useful. Even if the user has two imerges going at once, it is often clear which one is intended:

* From the `--name=NAME` option
* From the name of the current branch (if it is one of the temporary names that imerge sets up).

We could add a command `git imerge set-default NAME` to let the user choose a default branch explicitly (or just let the user run `git config imerge.default NAME`), and otherwise leave that setting alone.
